backend:
  name: github
  repo: GShadowBroker/Personal-Portfolio
  # name: test-repo
media_folder: static/assets
public_folder: /assets
collections:
  - name: page
    label: Page
    files:
      - name: content
        label: Content
        file: site/page/content.md
        fields:
          - { name: hero_description, label: Hero_Description, widget: string }
          - { name: about_me, label: About_Me, widget: string }
  - name: project
    label: Project
    folder: site/project
    create: true
    fields:
      - { name: title, label: Title }
      - { name: url, label: URL, required: false }
      - { name: repo, label: Repo }
      - {
          name: screenshot,
          label: Screenshot,
          widget: image,
          media_library: { config: { multiple: true } },
        }
      - { name: description, label: Description, widget: markdown }
      - { name: technologies, label: Technologies, widget: list }
